<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{ $report->title }}</title>
        <style>
            body{font-family: sans-serif; font-size: 14px; color: #333;}
            .header{text-align: center; margin-bottom: 40px; border-bottom:2px solid #eee; padding-bottom: 20px;}
            .header h1{margin: 0; color:#1a56db ; font-size: 24px;}
            .header h2{margin: 10px 0 5px 0; color:#333; font-size: 18px;}
            .meta-info{font-size: 12px; color:#666; line-height: 1.5;}
            table{width: 100%; border-collapse: collapse; margin-top: 20px;}
            th, td{border: 1px solid #ddd; padding: 12px; text-align: left;}
            th{width: 60%;background-color: #f8f9fa;color: #555;}
            td{width: 40%; font-weight: bold;}
            .highlight{background-color: #eff6ff; color: #1e40af;}
        </style>
    </head>

    <body>

        <div class="header">
            <h1>City Voice</h1>
            <h2>{{ $report->title }}</h2>
            <div class="meta-info">
                <strong>Data Period:</strong> {{ $report->metrics['period'] ?? 'N/A' }} <br>
                <strong>Generated By:</strong> {{ $report->generator->user->name ?? 'System' }} <br>
                <strong>Generated At:</strong> {{ $report->created_at->format('F d, Y h:i A') }} <br>
                <strong>Exported At:</strong> {{ now()->format('F d, Y h:i A') }}
            </div>
        </div>

        <table>
            <tbody>
                <tr>
                    <th>Total Complaints Recieved</th>
                    <td>{{ $report->metrics['total_received'] ?? 'N/A' }}</td>
                </tr>
                <tr class="highlight">
                    <th>Successfully Resolved</th>
                    <td>{{ $report->metrics['total_resolved'] ?? 'N/A' }}</td>
                </tr>
                <tr>
                    <th>Currently In Progress</th>
                    <td>{{ $report->metrics['total_in_progress'] ?? 'N/A' }}</td>
                </tr>
                <tr>
                    <th>Awaiting QA Approval</th>
                    <td>{{ $report->metrics['total_under_review'] ?? 'N/A' }}</td>
                </tr>
                <tr>
                    <th>Reopened</th>
                    <td>{{ $report->metrics['total_reopened'] ?? 'N/A' }}</td>
                </tr>
                <tr>
                    <th>Rejected</th>
                    <td>{{ $report->metrics['total_rejected'] ?? 'N/A' }}</td>
                </tr>
                <tr class="highlight">
                    <th>Resolution Rate</th>
                    <td>{{ $report->metrics['resolution_rate'] ?? 'N/A' }}%</td>
                </tr>
                <tr class="highlight">
                    <th>Avg. Hours to Resolve</th>
                    <td>{{ $report->metrics['avg_resolution_hours'] . ' ' . Str::plural('Hour', $report->metrics['avg_resolution_hours']) ?? 'N/A' }} </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
