<x-layout>
    @section('title', $report->title)

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        <a href="{{ route('admin.reports.index') }}" class="inline-flex items-center gap-2 text-sm mb-6 transition text-gray-600 hover:text-gray-900">
            <i class="fa-solid fa-arrow-left"></i> Back to Reports
        </a>

        <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-200 mb-8 flex justify-between items-center">
            <div>
                <h1 class="text-2xl font-bold text-gray-900">{{ $report->title }}</h1>
                <p class="text-sm text-gray-500 mt-1">
                    <i class="fa-regular fa-calendar mr-1"></i> Reporting Period: <span class="font-bold text-gray-700">{{ $report->metrics['period'] }}</span>
                </p>
            </div>
            <div class="text-right">
                <p class="text-xs text-gray-400 uppercase tracking-wider font-bold">Generated By</p>
                <p class="text-sm font-bold text-brand-dark">{{ $report->generator->user->name }}</p>
                <p class="text-xs text-gray-500">{{ $report->created_at->format('M d, Y h:i A') }}</p>
            </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            <div class="bg-linear-to-r from-brand-dark to-brand-blue rounded-xl p-6 shadow-sm text-white col-span-1 md:col-span-2 lg:col-span-4 flex items-center justify-between">
                <div>
                    <h3 class="text-white/80 font-bold uppercase tracking-wider text-sm mb-1">Average Lifecycle Response Time</h3>
                    <p class="text-4xl font-black">{{ $report->metrics['avg_resolution_hours'] === 0 ? 'N/A' : $report->metrics['avg_resolution_hours']  }} <span class="text-xl font-medium text-white/70">{{ Str::plural('Hour', $report->metrics['avg_resolution_hours']) }}</span></p>
                    <p class="text-sm text-white/60 mt-2">Average time from citizen submission to official admin closure.</p>
                </div>

                <div class="bg-white/10 p-4 rounded-full h-20 w-20 flex items-center justify-center">
                    <i class="fa-solid fa-stopwatch text-4xl text-brand-orange"></i>
                </div>
            </div>

            <div class="bg-white rounded-xl p-6 border border-gray-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-gray-600 font-bold uppercase tracking-wider text-xs">Total Complaints Recieved</h3>
                    <i class="fa-solid fa-inbox text-gray-400"></i>
                </div>
                <p class="text-3xl font-black text-gray-900">{{ $report->metrics['total_received'] === 0 ? 'N/A' : $report->metrics['total_received'] }}</p>
            </div>
            <div class="bg-white rounded-xl p-6 border border-green-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-green-600 font-bold uppercase tracking-wider text-xs">Successfully Resolved</h3>
                    <i class="fa-solid fa-check-double text-green-500"></i>
                </div>
                <p class="text-3xl font-black text-green-700">{{ $report->metrics['total_resolved'] === 0 ? 'N/A' : $report->metrics['total_resolved'] }}</p>
            </div>
            <div class="bg-white rounded-xl p-6 border border-blue-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-blue-600 font-bold uppercase tracking-wider text-xs">Resolution Rate</h3>
                    <i class="fa-solid fa-chart-pie text-brand-blue"></i>
                </div>
                <p class="text-3xl font-black text-brand-blue">{{ $report->metrics['resolution_rate'] === 0 ? 'N/A' : $report->metrics['resolution_rate']. '%' }}</p>
            </div>
            <div class="bg-white rounded-xl p-6 border border-yellow-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-yellow-600 font-bold uppercase tracking-wider text-xs">Awaiting Dispatch</h3>
                    <i class="fa-solid fa-hourglass-start text-yellow-500"></i>
                </div>
                <p class="text-3xl font-black text-yellow-700">{{ $report->metrics['total_pending'] === 0 ? 'N/A' : $report->metrics['total_pending'] }}</p>
            </div>
            <div class="bg-white rounded-xl p-6 border border-purple-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-purple-600 font-bold uppercase tracking-wider text-xs">Currently In Progress</h3>
                    <i class="fa-solid fa-hourglass-half text-purple-500"></i>
                </div>
                <p class="text-3xl font-black text-purple-700">{{ $report->metrics['total_in_progress'] === 0 ? 'N/A' : $report->metrics['total_in_progress'] }}</p>
            </div>
            <div class="bg-white rounded-xl p-6 border border-orange-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-orange-600 font-bold uppercase tracking-wider text-xs">Awaiting QA Review</h3>
                    <i class="fa-solid fa-hourglass-start text-orange-500"></i>
                </div>
                <p class="text-3xl font-black text-orange-700">{{ $report->metrics['total_under_review'] === 0 ? 'N/A' : $report->metrics['total_under_review'] }}</p>
            </div>
            <div class="bg-white rounded-xl p-6 border border-rose-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-rose-600 font-bold uppercase tracking-wider text-xs">Reopened (UnSolved)</h3>
                    <i class="fa-solid fa-arrow-rotate-left text-rose-500"></i>
                </div>
                <p class="text-3xl font-black text-rose-700">{{ $report->metrics['total_reopened'] === 0 ? 'N/A' : $report->metrics['total_reopened'] }}</p>
            </div>
            <div class="bg-white rounded-xl p-6 border border-red-200 shadow-sm flex flex-col justify-between">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="text-red-600 font-bold uppercase tracking-wider text-xs">Rejected / Invalid</h3>
                    <i class="fa-solid fa-ban text-red-500"></i>
                </div>
                <p class="text-3xl font-black text-red-700">{{ $report->metrics['total_rejected'] === 0 ? 'N/A' : $report->metrics['total_rejected']. '%' }}</p>
            </div>
        </div>

        <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-8">
            <h3 class="text-lg font-bold text-gray-900 mb-6 boder-b border-gray-100 pb-4">
                <i class="fa-solid fa-chart-pie text-brand-blue mr-2"></i> Pipeline Distribution Breakdown
            </h3>

            <div class="flex flex-col md:flex-row items-center justify-center gap-8">
                <div class="w-full md:w-1/2 relative h-75">
                    <canvas id="statusChart"></canvas>
                </div>

                <div class="w-full md:w-1/3 bg-gray-50 rounded-lg p-6 border border-gray-200">
                    <h4 class="font-bold text-gray-700 mb-2">Report Insights</h4>
                    <p class="text-sm text-gray-600 mb-4 leading-relaxed">
                        This chart visualizes the distribution of the <span class="font-bold text-gray-900">{{ $report->metrics['total_received'] ?? 0 }}</span> total {{ Str::plural('complaint',$report->metrics['total_received']) }} received during this period.
                    </p>

                    <ul class="text-sm space-y-2 text-gray-600">
                        <li><i class="fa-solid fa-circle text-green-500 text-[10px] mr-2"></i><span class="font-bold">{{ $report->metrics['resolution_rate'] === 0 ? 'N/A' : $report->metrics['resolution_rate'] . '%' }}</span> Success Rate</li>
                        <li><i class="fa-solid fa-circle text-red-500 text-[10px] mr-2"></i><span class="font-bold">{{ $report->metrics['total_rejected'] === 0 ? 'N/A' : $report->metrics['total_rejected'] . '%' }}</span> Rejected as Invalid</li>
                        <li><i class="fa-solid fa-circle text-brand-orange text-[10px] mr-2"></i><span class="font-bold">{{ $report->metrics['avg_resolution_hours'] === 0 ? 'N/A' : $report->metrics['avg_resolution_hours'] }}</span> Avg. {{ Str::plural('Hour',$report->metrics['avg_resolution_hours']) }} to Resolve</li>
                    </ul>
                </div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <script>
            document.addEventListener('DOMContentLoaded', function (){
                const ctx = document.getElementById('statusChart').getContext('2d')

                new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: ['Resolved', 'Pending', 'In Progress', 'Under Review', 'Reopened','Rejected'],
                        datasets:[{
                            data:[
                                {{ $report->metrics['total_resolved'] ?? 0 }},
                                {{ $report->metrics['total_pending'] ?? 0 }},
                                {{ $report->metrics['total_in_progress'] ?? 0 }},
                                {{ $report->metrics['total_under_review'] ?? 0 }},
                                {{ $report->metrics['total_reopened'] ?? 0 }},
                                {{ $report->metrics['total_rejected'] ?? 0 }}
                            ],
                            backgroundColor:[
                                '#16a34a',
                                '#ca8a04',
                                '#9333ea',
                                '#ea580c',
                                '#e11d48',
                                '#dc2626'
                            ],
                            borderWidth: 2,
                            borderColor: '#ffffff',
                            hoverOffset: 4
                        }]
                    },
                    options:{
                        responsive: true,
                        maintainAspectRatio: false,
                        cutout: '0',
                        plugins: {
                            legend:{
                                position: 'right',
                                labels:{
                                    usePointStyle: true,
                                    padding: 20,
                                    font:{
                                        family: 'Inter, sans-serif',
                                        size: 12,
                                    }
                                }
                            }

                        }
                    }
                });
            });
        </script>
    </div>
</x-layout>
